name: WorkFlow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run jest tests
        run: npm test

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run clean

  build:
    runs-on: ubuntu-latest
    needs: [test, prettier]
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --site 9624e242-ea23-44dc-9f62-e37017f405ee --auth nfp_wETampMUDGBpRcqpMnEiYTSTH94L1dEy571f--prod
