name: Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run jest tests
      run: npm test -- --verbose --ci --json --outputFile=test-report.json
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-report.json
        
    - name: Report Test Results
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Jest Tests
        path: test-report.json
        reporter: jest-json

    - name: Run prettier
      run: npm run clean