name: WorkFlow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  

      - name: Install dependencies
        run: npm ci

      - name: Run jest tests
        run: npm test
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run clean

  build:
    runs-on: ubuntu-latest
    needs: [jest, prettier]
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: true #if a job fails, the rest are cancelled
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify #this deploys to Netlify
        run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth  ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod